//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Wild_Animals_Capture_and_Shelter.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Animal
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public int GenderID { get; set; }
        public int SpeciesID { get; set; }
        public byte[] Photo { get; set; }
        public string Notes { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> ShelterID { get; set; }
    
        public virtual Gender Gender { get; set; }
        public virtual Shelter Shelter { get; set; }
        public virtual Species Species { get; set; }
        public virtual Status Status { get; set; }
    }
}
